/* eslint-disable @next/next/no-img-element */
"use client";

import { useState } from "react";
import type { CSSProperties } from "react";
import { BedDouble, Bot, CalendarDays, ChevronRight, Compass, Copy, ExternalLink, House, Images, MapPinned, MessageCircleMore, MoreHorizontal, PhoneCall, SignpostBig, UtensilsCrossed, Wifi, X } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { PublicGuideData, PublicGuideNavigationItem, PublicGuideQuickAction } from "@/features/public-guide/server/service";

type GuideHomeProps = { data: PublicGuideData };
type ThemeStyle = CSSProperties & Record<`--${string}`, string>;
type SheetKind = "wifi" | "accommodations" | "reservas" | "contact" | "map" | "gallery" | "food" | "tips" | "chat";

const iconMap = { bed: BedDouble, bot: Bot, calendar: CalendarDays, chat: MessageCircleMore, compass: Compass, gallery: Images, house: House, map: MapPinned, more: MoreHorizontal, phone: PhoneCall, signpost: SignpostBig, utensils: UtensilsCrossed, wifi: Wifi } as const;
const accentClasses = ["text-[#4eb5b3]", "text-[#e19442]", "text-[#4eb5b3]", "text-[#8d44a1]", "text-[#4eb5b3]", "text-[#e19442]", "text-[#e19442]", "text-[#4eb5b3]", "text-[#8d44a1]"];

function getIcon(name: string | null | undefined) { return iconMap[(name ?? "compass") as keyof typeof iconMap] ?? Compass; }
function themeStyle(data: PublicGuideData): ThemeStyle { return { "--background": data.theme.backgroundColor, "--foreground": data.theme.foregroundColor, "--card": data.theme.surfaceColor, "--card-foreground": data.theme.foregroundColor, "--primary": data.theme.primaryColor, "--secondary": data.theme.secondaryColor, "--accent": data.theme.accentColor, "--border": data.theme.borderColor, "--ring": data.theme.primaryColor }; }
function actionKind(action: PublicGuideQuickAction): SheetKind { const icon = action.icon.toLowerCase(); if (icon === "wifi") return "wifi"; if (icon === "bed") return "accommodations"; if (icon === "calendar") return "reservas"; if (icon === "phone") return "contact"; if (icon === "map") return "map"; if (icon === "gallery") return "gallery"; if (icon === "utensils") return "food"; if (icon === "signpost") return "tips"; return "chat"; }

function QuickActionGrid({ actions, onOpen }: { actions: PublicGuideQuickAction[]; onOpen: (kind: SheetKind) => void }) {
  return <div className="grid grid-cols-3 gap-2.5">{actions.map((action, index) => { const Icon = getIcon(action.icon); const accent = accentClasses[index % accentClasses.length]; return <button key={`${action.label}-${action.target}`} type="button" onClick={() => onOpen(actionKind(action))} className="flex min-h-[84px] flex-col items-center justify-center rounded-[18px] border border-[#efe2d5] bg-white px-1.5 py-3 text-center shadow-[0_9px_20px_rgba(117,95,74,0.08)] transition-transform active:scale-[0.98] hover:-translate-y-0.5"><Icon className={cn("mb-2 size-6", accent)} aria-hidden="true" /><span className={cn("text-[11px] font-medium leading-4", accent)}>{action.label}</span></button>; })}</div>;
}

function BottomNavigation({ items, onOpen }: { items: PublicGuideNavigationItem[]; onOpen: (kind: SheetKind) => void }) {
  return <nav className="border-t border-[#eadccd] bg-white/95 px-1.5 pb-[max(6px,env(safe-area-inset-bottom))] pt-1.5 backdrop-blur" aria-label="Navegação principal"><div className="grid grid-cols-5 gap-0.5">{items.slice(0, 5).map((item) => { const Icon = getIcon(item.icon); return <button key={item.id} type="button" onClick={() => item.destination === "#topo" ? window.scrollTo({ top: 0, behavior: "smooth" }) : onOpen(item.destination === "#concierge" ? "chat" : "tips")} className={cn("flex min-h-[48px] flex-col items-center justify-center gap-0.5 rounded-[13px] px-1 text-[9px] font-medium text-[#7b6c62]", item.highlighted && "bg-[#5ec5c0] text-white")}><Icon className="size-4" aria-hidden="true" /><span>{item.label}</span></button>; })}</div></nav>;
}

function GuideSheet({ kind, data, onClose }: { kind: SheetKind; data: PublicGuideData; onClose: () => void }) {
  const reservationHref = data.booking.href ?? "#";
  const title = { wifi: "Wi-Fi", accommodations: "Acomodações", reservas: "Reservas", contact: "Contato", map: "Como chegar", gallery: "Galeria", food: "Gastronomia", tips: "Dicas da região", chat: "Concierge 24h" }[kind];
  const copyPassword = () => navigator.clipboard?.writeText("Será configurado pelo estabelecimento");
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#2f2724]/35 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="guide-sheet-title" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="max-h-[88dvh] w-full max-w-[520px] overflow-y-auto rounded-t-[28px] bg-[#fffdfa] shadow-[0_-20px_70px_rgba(67,47,36,0.22)] sm:rounded-[28px]"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#eee1d5] bg-[#fffdfa]/95 px-5 py-4 backdrop-blur"><div><span className="mb-1 block h-1 w-9 rounded-full bg-[#d8c7b8] sm:hidden" /><h2 id="guide-sheet-title" className="text-xl font-semibold text-[#543f39]">{title}</h2></div><button type="button" onClick={onClose} aria-label="Fechar" className="rounded-full p-2 text-[#6e5a51] hover:bg-[#f6eee7]"><X className="size-5" /></button></div><div className="space-y-4 px-5 pb-7 pt-5 text-sm leading-6 text-[#715c53]">
    {kind === "wifi" && <><p>A rede e a senha serão configuradas pelo estabelecimento.</p><div className="rounded-2xl bg-[#f8efe6] p-4"><p className="text-xs uppercase tracking-[.18em] text-[#a18c7d]">Rede</p><p className="font-medium text-[#543f39]">Não informada</p><p className="mt-3 text-xs uppercase tracking-[.18em] text-[#a18c7d]">Senha</p><p className="font-medium text-[#543f39]">••••••••</p></div><button type="button" onClick={copyPassword} className={cn(buttonVariants({ variant: "outline" }), "h-10 w-full rounded-full")}>Copiar senha <Copy className="size-4" /></button></>}
    {kind === "accommodations" && (data.accommodations.length ? data.accommodations.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-[#eadccd]">{item.imageUrl && <img src={item.imageUrl} alt={item.name} className="aspect-[16/9] w-full object-cover" />}<div className="p-4"><h3 className="text-lg font-semibold text-[#543f39]">{item.name}</h3><p className="mt-1">{item.short_description ?? "Descrição em configuração."}</p>{item.capacity && <p className="mt-2 text-xs text-[#957e70]">Capacidade: {item.capacity}</p>}<a href={item.booking_url ?? reservationHref} target="_blank" rel="noreferrer" className={cn(buttonVariants({ size: "sm" }), "mt-4 rounded-full bg-[#5ec5c0] text-white")}>Ver detalhes / Reservar <ChevronRight className="size-4" /></a></div></article>) : <p>Nenhuma acomodação publicada ainda.</p>)}
    {kind === "reservas" && <><p>{data.booking.helperText ?? "Consulte disponibilidade e faça sua reserva pelo canal oficial."}</p><a href={reservationHref} target="_blank" rel="noreferrer" className={cn(buttonVariants({ size: "lg" }), "w-full rounded-full bg-[#8d44a1] text-white")}>{data.booking.label} <ExternalLink className="size-4" /></a>{data.contact.phone && <a href={`tel:${data.contact.phone}`} className="block text-center font-medium text-[#4eb5b3]">{data.contact.phone}</a>}</>}
    {kind === "contact" && <div className="space-y-2">{data.contact.phone && <a href={`tel:${data.contact.phone}`} className="flex items-center gap-3 rounded-2xl bg-[#f8efe6] p-4"><PhoneCall className="size-5 text-[#4eb5b3]" />{data.contact.phone}</a>}{data.contact.email && <a href={`mailto:${data.contact.email}`} className="block rounded-2xl bg-[#f8efe6] p-4">{data.contact.email}</a>}</div>}
    {kind === "map" && <><p>{data.contact.address ?? "Endereço será configurado pelo estabelecimento."}</p>{data.contact.address && <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.contact.address)}`} target="_blank" rel="noreferrer" className={cn(buttonVariants({ size: "lg" }), "w-full rounded-full bg-[#5ec5c0] text-white")}>Abrir no mapa <ExternalLink className="size-4" /></a>}</>}
    {kind === "gallery" && (data.gallery.length ? <div className="grid grid-cols-2 gap-2">{data.gallery.map((item) => <img key={item.id} src={item.imageUrl} alt={item.caption ?? "Galeria"} className="aspect-square w-full rounded-2xl object-cover" loading="lazy" />)}</div> : <p>A galeria será configurada pelo estabelecimento.</p>)}
    {kind === "food" && <><h3 className="text-lg font-semibold text-[#543f39]">{data.breakfast?.title ?? "Gastronomia"}</h3><p>{data.breakfast?.body ?? "As informações de gastronomia serão configuradas pelo estabelecimento."}</p></>}
    {kind === "tips" && (data.localTips.length ? data.localTips.map((tip) => <article key={tip.id} className="rounded-2xl bg-[#f8efe6] p-4"><h3 className="font-semibold text-[#543f39]">{tip.name}</h3><p>{tip.short_description ?? tip.description ?? "Informação em configuração."}</p></article>) : <p>As dicas da região serão configuradas pelo estabelecimento.</p>)}
    {kind === "chat" && <div className="min-h-[45dvh] space-y-3 rounded-2xl bg-[#f8efe6] p-4"><div className="max-w-[88%] rounded-2xl bg-white p-3">Olá! Como posso ajudar durante sua estadia?</div><div className="ml-auto max-w-[88%] rounded-2xl bg-[#5ec5c0] p-3 text-white">O Concierge visual estará conectado aos dados do estabelecimento em uma próxima etapa.</div></div>}
  </div></section></div>;
}

export function GuideHome({ data }: GuideHomeProps) {
  const [sheet, setSheet] = useState<SheetKind | null>(null);
  const greeting = `${data.greeting}, ${data.design.heroTitle ?? "bem-vindo(a)"}`;
  return <main style={themeStyle(data)} className="min-h-dvh overflow-x-hidden bg-[linear-gradient(180deg,#fdf8f2_0%,#f8f1e9_100%)] text-foreground"><div className="mx-auto min-h-dvh w-full max-w-[440px] px-3 pb-3 pt-3 sm:pt-6"><div className="overflow-hidden rounded-[34px] border border-[#e8d9ca] bg-[#fffdfa] shadow-[0_24px_70px_rgba(118,94,70,0.16)]"><div className="flex items-center justify-between px-5 pb-2 pt-4 text-xs text-[#493a34]"><span className="font-semibold">09:41</span><span className="uppercase tracking-[.18em] text-[#a48f82]">Guia Digital</span></div><div id="topo" className="px-4 pb-4"><div className="rounded-[26px] bg-[linear-gradient(180deg,#f8efe4_0%,#fff9f5_100%)] px-3 pb-4 pt-3">{data.branding.logoPath && <img src={data.branding.logoPath} alt={data.tenant.name} className="mx-auto h-auto w-[190px] max-w-full" />}<div className="mt-2 text-center"><p className="text-xs font-medium text-[#8a6f67]">{greeting}</p><h1 className="mt-1 text-[25px] font-semibold leading-none text-[#7d3b95]">{data.design.heroTitle ?? "Bem-vindo(a)!"}</h1><p className="mt-1 text-base font-medium text-[#4b3b35]">{data.design.heroSubtitle ?? "Sua experiência começa aqui."}</p></div><div className="relative mt-3 overflow-hidden rounded-[24px]">{data.design.heroImagePath && <img src={data.design.heroImagePath} alt={data.tenant.name} className="aspect-[16/9] w-full object-cover" />}{data.design.heroLineImagePath && <img src={data.design.heroLineImagePath} alt="" className="absolute bottom-0 left-0 w-full" />}</div></div><div id="explorar" className="mt-3"><QuickActionGrid actions={data.quickActions} onOpen={setSheet} /></div><p className="px-2 pb-0 pt-3 text-center font-serif text-[21px] italic leading-tight text-[#7aaea8]">{data.design.signature ?? "A natureza inspira. Aqui, você se conecta."}</p></div><BottomNavigation items={data.navigation} onOpen={setSheet} /></div></div>{sheet && <GuideSheet kind={sheet} data={data} onClose={() => setSheet(null)} />}</main>;
}
