import Link from "next/link";
import { Archive, ArrowUpRight, Building2, CheckCircle2, FileEdit, Plus } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { getSuperAdminDashboard } from "@/features/super-admin/server/service";

const statusLabels: Record<string, string> = { draft: "Rascunho", active: "Ativo", suspended: "Suspenso", archived: "Arquivado" };
const statusClasses: Record<string, string> = { draft: "bg-amber-50 text-amber-700 ring-amber-200", active: "bg-emerald-50 text-emerald-700 ring-emerald-200", suspended: "bg-orange-50 text-orange-700 ring-orange-200", archived: "bg-slate-100 text-slate-600 ring-slate-200" };

function Metric({ label, value, icon: Icon, tone }: { label: string; value: number; icon: typeof Building2; tone: string }) {
  return <Card className="border-[var(--rf-border)] shadow-[0_8px_24px_rgba(7,26,58,.05)]"><CardContent className="flex items-center gap-4 p-5"><span className={cn("flex size-11 items-center justify-center rounded-xl", tone)}><Icon className="size-5" /></span><div><p className="text-sm text-[var(--rf-muted)]">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight text-[var(--rf-text)]">{value}</p></div></CardContent></Card>;
}

export default async function SuperAdminPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const dashboard = await getSuperAdminDashboard();
  const { status: feedbackStatus } = await searchParams;
  const archived = dashboard.tenants.filter((tenant) => tenant.status === "archived").length;
  return <div className="mx-auto max-w-7xl space-y-8">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[var(--rf-primary)]">Visão geral</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[var(--rf-text)]">Visão Geral</h1><p className="mt-2 text-sm text-[var(--rf-muted)]">Gerencie os estabelecimentos da plataforma RF Tecnologia.</p></div><Link href="/super-admin/estabelecimentos/novo" className={cn(buttonVariants(), "h-11 w-fit bg-[var(--rf-primary)] px-4 text-white shadow-lg shadow-blue-700/20 hover:bg-[var(--rf-navy)]")}><Plus className="size-4" />Novo estabelecimento</Link></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total de estabelecimentos" value={dashboard.total} icon={Building2} tone="bg-blue-50 text-[var(--rf-primary)]" /><Metric label="Ativos" value={dashboard.active} icon={CheckCircle2} tone="bg-emerald-50 text-emerald-600" /><Metric label="Em configuração" value={dashboard.drafts} icon={FileEdit} tone="bg-amber-50 text-amber-600" /><Metric label="Arquivados" value={archived} icon={Archive} tone="bg-slate-100 text-slate-500" /></div>
    <section className="space-y-4">{feedbackStatus ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{feedbackStatus === "publicado" ? "Estabelecimento publicado com sucesso." : feedbackStatus === "arquivado" ? "Estabelecimento arquivado." : "Estabelecimento restaurado."}</div> : null}<div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold text-[var(--rf-text)]">Estabelecimentos</h2><p className="mt-1 text-sm text-[var(--rf-muted)]">Todos os estabelecimentos cadastrados na plataforma.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-[var(--rf-primary)]">{dashboard.total} cadastrados</span></div>{dashboard.tenants.length === 0 ? <Card className="border-dashed border-[var(--rf-border)]"><CardContent className="p-10 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-blue-50 text-[var(--rf-primary)]"><Building2 className="size-5" /></span><p className="mt-4 font-semibold text-[var(--rf-text)]">Nenhum estabelecimento cadastrado.</p><p className="mt-1 text-sm text-[var(--rf-muted)]">Comece criando o primeiro estabelecimento da plataforma.</p></CardContent></Card> : <div className="grid gap-3">{dashboard.tenants.map((tenant) => <Card key={tenant.id} className="border-[var(--rf-border)] shadow-[0_8px_24px_rgba(7,26,58,.04)] transition hover:border-blue-200 hover:shadow-[0_12px_30px_rgba(7,26,58,.08)]"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><span className="hidden size-10 items-center justify-center rounded-xl bg-blue-50 text-[var(--rf-primary)] sm:flex"><Building2 className="size-4" /></span><div className="min-w-0"><h3 className="truncate font-semibold text-[var(--rf-text)]">{tenant.name}</h3><p className="mt-1 truncate text-sm text-[var(--rf-muted)]">/{tenant.slug} · Criado em {new Intl.DateTimeFormat("pt-BR").format(new Date(tenant.created_at))}</p></div></div><div className="flex items-center justify-between gap-3 sm:justify-end"><span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold ring-1", statusClasses[tenant.status] ?? "bg-slate-100 text-slate-600 ring-slate-200")}>{statusLabels[tenant.status] ?? tenant.status}</span><Link href={`/super-admin/estabelecimentos/${tenant.slug}`} className={cn(buttonVariants({ variant: "outline", size: "sm" }), "border-[var(--rf-border)] text-[var(--rf-primary)] hover:bg-blue-50")}>Gerenciar<ArrowUpRight className="size-3.5" /></Link></div></CardContent></Card>)}</div>}</section>
  </div>;
}
